### ISSUE TITLE
Support for functions or expressions?

### ISSUE THREAD

**Issue by bergonzzi** [jasonxunxu/dokuwiki-plugin-c3chart#9]
Hi, is there any way to allow functions or expressions to be used? I was trying to configure an axis as a percentage using:

    tick: {
        format: d3.format("%")
    }

 but this doesn't work, I get a `string is not a function'` error in the console. I think this is what you refer to in the documentation that it's for security reasons, but is there a way to overcome that? In my case it's an internal wiki and security isn't a concern.

**Comment by jasonxunxu** [comment]
Since this is a wiki plugin, as you noticed it would be a severe security issue if arbitrary JavaScript functions could be evaluated inside the user supplied data. If you are pretty sure that this is not a problem for your case you can modify `script.js`, and evaluate (`eval()`) the part of the loaded data that you would expect to be a function, before create the `c3` object with `c3.generate`.
